import { LIGHT_COLORS, type CatalogEntry, type LightSpec, type Material } from './schema.js';

/** 自產參數化模組：專案自有，可商用（登記於 docs/licenses.md） */
export const OWN_LICENSE = {
  type: 'proprietary-own',
  source: 'InteriorAI 自產參數化模組',
  allowedUse: ['commercial', 'render', 'redistribute'],
} as const satisfies CatalogEntry['license'];

const int = (min: number, max: number, def: number, labelKey: string) =>
  ({ type: 'integer', min, max, default: def, labelKey }) as const;

type P = CatalogEntry['model'] & { kind: 'parametric' };
const pm = (type: P['type'], params: P['params'] = {}): P => ({ kind: 'parametric', type, params });
const sizeParams = (w: number, d: number, h: number) => ({
  w: int(Math.round(w * 0.5), Math.round(w * 2), w, 'param.width'),
  d: int(Math.round(d * 0.5), Math.round(d * 2), d, 'param.depth'),
  h: int(Math.round(h * 0.5), Math.round(h * 2), h, 'param.height'),
});

function e(
  slug: string,
  nameZh: string,
  nameEn: string,
  category: CatalogEntry['category'],
  dims: [number, number, number],
  model: P,
  opts: Partial<CatalogEntry> = {},
): CatalogEntry {
  const [w, d, h] = dims;
  const params = Object.keys(model.params).length ? model.params : sizeParams(w, d, h);
  return {
    id: slug,
    slug,
    nameZh,
    nameEn,
    category,
    tags: [],
    styleTags: ['modern'],
    dimsMm: { w, d, h },
    anchor: 'floor',
    model: { ...model, params },
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_wood_oak' }],
    license: OWN_LICENSE,
    status: 'published',
    ...opts,
  };
}

/** 燈具：共用 color（光色）與 dimmer（調光）參數；外殼材質預設黑色金屬 */
function lamp(
  slug: string,
  nameZh: string,
  nameEn: string,
  dims: [number, number, number],
  type: P['type'],
  color: (typeof LIGHT_COLORS)[number],
  light: Omit<LightSpec, 'facing' | 'castShadow'> & Partial<Pick<LightSpec, 'facing' | 'castShadow'>>,
  opts: Partial<CatalogEntry> = {},
): CatalogEntry {
  const [w, d, h] = dims;
  return e(
    slug,
    nameZh,
    nameEn,
    'lighting',
    dims,
    pm(type, {
      ...sizeParams(w, d, h),
      color: { type: 'enum', values: [...LIGHT_COLORS], default: color, labelKey: 'param.lightColor' },
      dimmer: int(0, 100, 100, 'param.dimmer'),
    }),
    {
      tags: ['燈', 'light'],
      light: { facing: 'down', castShadow: false, ...light },
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_metal_black' }],
      ...opts,
    },
  );
}

/** 門窗樣式參數（FE-PLAN-04） */
const styleParam = (def: string, values: string[]) =>
  ({ type: 'enum', values, default: def, labelKey: 'param.style' }) as const;
const DOOR_STYLES = ['single', 'double', 'unequal', 'sliding', 'folding', 'pocket', 'arch'];
const WINDOW_STYLES = ['sliding', 'casement', 'fixed', 'awning', 'bay', 'corner', 'arch'];

const ENTRIES: CatalogEntry[] = [
  // 門窗（依附牆）
  e(
    'door_single_900',
    '單開門 90',
    'Single door 90',
    'openings',
    [900, 40, 2100],
    pm('door', {
      w: int(600, 1200, 900, 'param.width'),
      h: int(1800, 2400, 2100, 'param.height'),
      swing: { type: 'enum', values: ['left', 'right'], default: 'left', labelKey: 'param.swing' },
    }),
    { anchor: 'wall', tags: ['door', '門'] },
  ),
  e(
    'door_double_1500',
    '雙開門 150',
    'Double door 150',
    'openings',
    [1500, 40, 2100],
    pm('door', {
      w: int(1200, 2000, 1500, 'param.width'),
      h: int(1800, 2400, 2100, 'param.height'),
      swing: { type: 'enum', values: ['double'], default: 'double', labelKey: 'param.swing' },
    }),
    { anchor: 'wall', tags: ['door', '門'] },
  ),
  e(
    'window_1200',
    '窗 120',
    'Window 120',
    'openings',
    [1200, 80, 1200],
    pm('window', {
      w: int(400, 3000, 1200, 'param.width'),
      h: int(400, 2400, 1200, 'param.height'),
      sill: int(0, 1500, 900, 'param.sill'),
      panes: int(1, 4, 2, 'param.panes'),
    }),
    { anchor: 'wall', tags: ['window', '窗'] },
  ),
  e(
    'window_1800',
    '落地窗 180',
    'Floor window 180',
    'openings',
    [1800, 80, 2100],
    pm('window', {
      w: int(600, 4000, 1800, 'param.width'),
      h: int(1000, 2600, 2100, 'param.height'),
      sill: int(0, 600, 0, 'param.sill'),
      panes: int(1, 6, 3, 'param.panes'),
    }),
    { anchor: 'wall', tags: ['window', '窗'] },
  ),
  // 系統櫃
  e(
    'cabinet_wardrobe_1800',
    '系統衣櫃 180',
    'Wardrobe 180',
    'storage',
    [1800, 600, 2400],
    pm('cabinet', {
      w: int(400, 3600, 1800, 'param.width'),
      d: int(300, 700, 600, 'param.depth'),
      h: int(600, 2700, 2400, 'param.height'),
      doors: int(0, 6, 3, 'param.doors'),
      shelves: int(0, 8, 4, 'param.shelves'),
    }),
    { tags: ['衣櫃', 'wardrobe'] },
  ),
  e(
    'cabinet_shoe_1200',
    '鞋櫃 120',
    'Shoe cabinet 120',
    'entry',
    [1200, 380, 1100],
    pm('cabinet', {
      w: int(400, 2400, 1200, 'param.width'),
      d: int(300, 450, 380, 'param.depth'),
      h: int(600, 2400, 1100, 'param.height'),
      doors: int(0, 4, 2, 'param.doors'),
      shelves: int(0, 8, 4, 'param.shelves'),
    }),
    { tags: ['鞋櫃'] },
  ),
  e(
    'cabinet_book_900',
    '書櫃 90',
    'Bookcase 90',
    'office',
    [900, 350, 2000],
    pm('cabinet', {
      w: int(400, 2400, 900, 'param.width'),
      d: int(250, 450, 350, 'param.depth'),
      h: int(600, 2400, 2000, 'param.height'),
      doors: int(0, 4, 0, 'param.doors'),
      shelves: int(1, 8, 5, 'param.shelves'),
    }),
    { tags: ['書櫃', 'bookcase'] },
  ),
  e(
    'cabinet_sideboard_1600',
    '餐邊櫃 160',
    'Sideboard 160',
    'dining',
    [1600, 450, 850],
    pm('cabinet', {
      w: int(600, 2400, 1600, 'param.width'),
      d: int(350, 600, 450, 'param.depth'),
      h: int(600, 1200, 850, 'param.height'),
      doors: int(0, 6, 4, 'param.doors'),
      shelves: int(0, 3, 1, 'param.shelves'),
    }),
  ),
  // 客廳
  e('sofa_3seat_a', '三人沙發', '3-seat sofa', 'living', [2100, 900, 820], pm('sofa'), {
    tags: ['沙發', 'sofa'],
    unitPriceTwd: 28000,
  }),
  e('sofa_2seat_a', '雙人沙發', '2-seat sofa', 'living', [1600, 880, 820], pm('sofa'), {
    tags: ['沙發', 'sofa'],
  }),
  e('armchair_a', '單椅', 'Armchair', 'living', [800, 820, 800], pm('sofa'), { tags: ['單椅'] }),
  e('table_coffee_a', '茶几', 'Coffee table', 'living', [1100, 600, 420], pm('table'), { tags: ['茶几'] }),
  e('table_side_a', '邊几', 'Side table', 'living', [450, 450, 550], pm('table'), { tags: ['邊几'] }),
  e('tvstand_1800', '電視櫃 180', 'TV stand 180', 'living', [1800, 420, 500], pm('tvstand'), {
    tags: ['電視櫃'],
  }),
  e('rug_2000', '地毯 200×140', 'Rug 200x140', 'decor', [2000, 1400, 10], pm('rug'), {
    tags: ['地毯'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_fabric_beige' }],
  }),
  // 餐廳
  e('table_dining_4', '四人餐桌', 'Dining table 4', 'dining', [1400, 800, 750], pm('table'), {
    tags: ['餐桌'],
  }),
  e('table_dining_6', '六人餐桌', 'Dining table 6', 'dining', [1800, 900, 750], pm('table'), {
    tags: ['餐桌'],
  }),
  e('chair_dining_a', '餐椅', 'Dining chair', 'dining', [450, 520, 820], pm('chair'), {
    tags: ['餐椅', 'chair'],
  }),
  // 臥室
  e('bed_double_150', '雙人床 150', 'Double bed 150', 'bedroom', [1600, 2100, 1000], pm('bed'), {
    tags: ['床', 'bed'],
  }),
  e('bed_queen_180', '加大雙人床 180', 'Queen bed 180', 'bedroom', [1900, 2150, 1050], pm('bed'), {
    tags: ['床', 'bed'],
  }),
  e('bed_single_90', '單人床 90', 'Single bed 90', 'bedroom', [1000, 2000, 900], pm('bed'), {
    tags: ['床', 'bed'],
  }),
  e('nightstand_a', '床頭櫃', 'Nightstand', 'bedroom', [450, 400, 500], pm('nightstand'), {
    tags: ['床頭櫃'],
  }),
  e('desk_dresser_a', '梳妝台', 'Dresser', 'bedroom', [1000, 450, 760], pm('desk'), { tags: ['梳妝台'] }),
  // 書房
  e('desk_office_1400', '辦公桌 140', 'Desk 140', 'office', [1400, 700, 750], pm('desk'), {
    tags: ['書桌', 'desk'],
  }),
  e('chair_office_a', '辦公椅', 'Office chair', 'office', [600, 600, 1100], pm('chair'), {
    tags: ['辦公椅'],
  }),
  e('shelf_open_800', '開放層架', 'Open shelf', 'office', [800, 300, 1800], pm('shelf'), { tags: ['層架'] }),
  // 廚房
  e('counter_base_600', '廚具下櫃 60', 'Base cabinet 60', 'kitchen', [600, 600, 850], pm('counter'), {
    tags: ['廚具'],
  }),
  e('counter_base_900', '廚具下櫃 90', 'Base cabinet 90', 'kitchen', [900, 600, 850], pm('counter'), {
    tags: ['廚具'],
  }),
  e('fridge_a', '冰箱', 'Refrigerator', 'kitchen', [700, 700, 1800], pm('fridge'), { tags: ['冰箱'] }),
  e('island_1500', '中島', 'Kitchen island', 'kitchen', [1500, 900, 900], pm('counter'), { tags: ['中島'] }),
  // 衛浴
  e('toilet_a', '馬桶', 'Toilet', 'bathroom', [380, 700, 780], pm('toilet'), { tags: ['馬桶'] }),
  e('basin_a', '洗手台', 'Basin', 'bathroom', [600, 480, 850], pm('basin'), { tags: ['洗手台'] }),
  e('bathtub_1600', '浴缸 160', 'Bathtub 160', 'bathroom', [1600, 750, 560], pm('bathtub'), {
    tags: ['浴缸'],
  }),
  // 燈具（光源規格 light：lm、發光位置、光束角/發光面；參數 color/dimmer）與裝飾
  lamp('lamp_floor_a', '立燈', 'Floor lamp', [400, 400, 1600], 'lamp_floor', '2700K', {
    kind: 'point',
    lumens: 900,
    offset: [0, 1450, 0],
    castShadow: true,
  }),
  lamp(
    'lamp_pendant_a',
    '吊燈',
    'Pendant lamp',
    [500, 500, 400],
    'lamp_pendant',
    '3000K',
    {
      kind: 'point',
      lumens: 1100,
      offset: [0, 60, 0],
      castShadow: true,
    },
    { anchor: 'ceiling' },
  ),
  lamp('lamp_table_a', '檯燈', 'Table lamp', [280, 280, 460], 'lamp_table', '2700K', {
    kind: 'point',
    lumens: 450,
    offset: [0, 360, 0],
    castShadow: true,
  }),
  lamp(
    'lamp_wall_a',
    '壁燈',
    'Wall sconce',
    [220, 160, 260],
    'lamp_wall',
    '2700K',
    {
      kind: 'point',
      lumens: 400,
      offset: [0, 170, 90],
    },
    { anchor: 'wall', elevationMm: 1450 },
  ),
  lamp(
    'lamp_downlight_a',
    '崁燈',
    'Downlight',
    [110, 110, 60],
    'lamp_downlight',
    '3000K',
    {
      kind: 'spot',
      lumens: 650,
      offset: [0, 0, 0],
      beamDeg: 70,
      castShadow: true,
    },
    { anchor: 'ceiling' },
  ),
  lamp(
    'lamp_track_a',
    '軌道投射燈',
    'Track spotlight',
    [900, 70, 180],
    'lamp_track',
    '3000K',
    {
      kind: 'spot',
      lumens: 900,
      offset: [0, 0, 60],
      beamDeg: 36,
      castShadow: true,
    },
    { anchor: 'ceiling' },
  ),
  lamp(
    'lamp_chandelier_a',
    '主燈吊燈',
    'Chandelier',
    [800, 800, 650],
    'lamp_chandelier',
    '2700K',
    {
      kind: 'point',
      lumens: 2400,
      offset: [0, 200, 0],
      castShadow: true,
    },
    { anchor: 'ceiling' },
  ),
  lamp('lamp_arc_a', '弧形立燈', 'Arc floor lamp', [1300, 400, 2000], 'lamp_arc', '2700K', {
    kind: 'spot',
    lumens: 1000,
    offset: [520, 1800, 0],
    beamDeg: 90,
    castShadow: true,
  }),
  lamp(
    'light_hex_a',
    '六角燈板',
    'Hexagon light panels',
    [620, 30, 420],
    'light_hex',
    'magenta',
    {
      kind: 'area',
      lumens: 350,
      offset: [0, 210, 30],
      size: { w: 560, h: 380 },
      facing: 'front',
    },
    { anchor: 'wall', elevationMm: 1150 },
  ),
  lamp('led_strip_1000', 'LED 燈條 1m', 'LED strip 1m', [1000, 20, 12], 'led_strip', 'amber', {
    kind: 'area',
    lumens: 400,
    offset: [0, 6, 0],
    size: { w: 1000, h: 16 },
    facing: 'up',
  }),
  lamp('led_bar_1200', 'LED 直立燈條', 'LED light bar', [60, 60, 1200], 'led_bar', 'pink', {
    kind: 'area',
    lumens: 500,
    offset: [0, 600, 30],
    size: { w: 30, h: 1150 },
    facing: 'front',
  }),
  lamp(
    'monitor_27',
    '螢幕 27 吋',
    'Monitor 27"',
    [620, 200, 460],
    'monitor',
    '6500K',
    {
      kind: 'area',
      lumens: 220,
      offset: [0, 280, 35],
      size: { w: 600, h: 340 },
      facing: 'front',
    },
    { category: 'office' },
  ),
  e('curtain_pair', '窗簾（一對）', 'Curtains', 'decor', [2000, 160, 2500], pm('curtain'), {
    anchor: 'wall',
    tags: ['窗簾'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_fabric_charcoal' }],
  }),
  e('plant_a', '盆栽', 'Plant', 'decor', [450, 450, 1200], pm('plant'), { tags: ['植物'] }),

  // ── v1.1 擴充家具（ADR-023）──────────────────────────────
  // 客廳
  e('sofa_l_2700', 'L 型沙發', 'L-shaped sectional', 'living', [2700, 1700, 820], pm('sofa_l'), {
    tags: ['沙發', 'sofa', 'sectional'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_fabric_grey' }],
  }),
  e('sofa_leather_3', '皮革三人沙發', 'Leather sofa', 'living', [2200, 950, 800], pm('sofa'), {
    tags: ['沙發', 'sofa', 'leather'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_leather_cognac' }],
  }),
  e('armchair_velvet', '絨布單椅', 'Velvet armchair', 'living', [780, 800, 820], pm('sofa'), {
    tags: ['單椅'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_velvet_green' }],
  }),
  e('ottoman_round', '圓形腳凳', 'Round ottoman', 'living', [550, 550, 420], pm('ottoman'), {
    tags: ['腳凳', 'pouf'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_fabric_beige' }],
  }),
  e('bean_bag_a', '懶骨頭', 'Bean bag', 'living', [900, 900, 700], pm('bean_bag'), {
    tags: ['懶骨頭'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_velvet_rust' }],
  }),
  e('floor_cushion_a', '和室坐墊', 'Floor cushion', 'living', [600, 600, 120], pm('floor_cushion'), {
    tags: ['坐墊'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_fabric_beige' }],
  }),
  e('table_coffee_round', '圓形茶几', 'Round coffee table', 'living', [900, 900, 400], pm('table_round'), {
    tags: ['茶几'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_stone_marble' }],
  }),
  e('tv_65', '電視 65 吋', 'TV 65"', 'living', [1450, 80, 840], pm('tv'), { tags: ['電視', 'tv'] }),
  e('tv_55_wall', '壁掛電視 55 吋', 'Wall TV 55"', 'living', [1230, 60, 710], pm('tv'), {
    anchor: 'wall',
    elevationMm: 1000,
    tags: ['電視', 'tv'],
  }),
  e('piano_upright', '直立式鋼琴', 'Upright piano', 'living', [1500, 600, 1250], pm('piano'), {
    tags: ['鋼琴'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_lacquer_black' }],
  }),
  lamp(
    'fireplace_electric',
    '壁爐',
    'Fireplace',
    [1400, 400, 1100],
    'fireplace',
    'amber',
    { kind: 'point', lumens: 700, offset: [0, 350, 120], castShadow: true },
    {
      category: 'living',
      tags: ['壁爐', 'fireplace'],
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_stone_marble' }],
    },
  ),
  e('rug_round_2000', '圓形地毯 Ø200', 'Round rug 200', 'decor', [2000, 2000, 10], pm('rug_round'), {
    tags: ['地毯'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_fabric_grey' }],
  }),
  e('rug_3000', '大地毯 300×200', 'Rug 300x200', 'decor', [3000, 2000, 10], pm('rug'), {
    tags: ['地毯'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_fabric_charcoal' }],
  }),
  // 餐廚
  e('table_dining_round', '圓餐桌', 'Round dining table', 'dining', [1200, 1200, 750], pm('table_round'), {
    tags: ['餐桌'],
  }),
  e('bench_dining', '餐椅長凳', 'Dining bench', 'dining', [1400, 380, 450], pm('bench'), { tags: ['長凳'] }),
  e('stool_bar', '吧檯椅', 'Bar stool', 'kitchen', [420, 420, 750], pm('stool'), {
    tags: ['吧檯椅', 'stool'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_metal_brass' }],
  }),
  e('bar_counter_1800', '吧檯', 'Bar counter', 'kitchen', [1800, 500, 1050], pm('counter'), {
    tags: ['吧檯'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_wood_dark' }],
  }),
  e('stove_600', '瓦斯爐台', 'Cooktop base', 'kitchen', [600, 600, 850], pm('stove'), {
    tags: ['爐台', 'stove'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_paint_white' }],
  }),
  e('sink_900', '水槽櫃', 'Sink cabinet', 'kitchen', [900, 600, 850], pm('sink'), {
    tags: ['水槽', 'sink'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_paint_white' }],
  }),
  e('upper_cabinet_900', '廚具吊櫃 90', 'Wall cabinet 90', 'kitchen', [900, 350, 700], pm('upper_cabinet'), {
    anchor: 'wall',
    elevationMm: 1450,
    tags: ['吊櫃'],
  }),
  e('range_hood_900', '排油煙機', 'Range hood', 'kitchen', [900, 500, 600], pm('range_hood'), {
    anchor: 'wall',
    elevationMm: 1500,
    tags: ['排油煙機'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_metal_steel' }],
  }),
  e('cabinet_pantry_600', '高櫃（電器櫃）', 'Tall pantry', 'kitchen', [600, 600, 2200], pm('cabinet'), {
    tags: ['高櫃'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_paint_white' }],
  }),
  e('washer_a', '滾筒洗衣機', 'Washing machine', 'bathroom', [600, 600, 850], pm('washer'), {
    tags: ['洗衣機'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_paint_white' }],
  }),
  // 臥室
  e('dresser_1200', '五斗櫃', 'Chest of drawers', 'bedroom', [1200, 480, 850], pm('dresser'), {
    tags: ['斗櫃'],
  }),
  e('bed_king_200', '特大雙人床 200', 'King bed 200', 'bedroom', [2100, 2200, 1100], pm('bed'), {
    tags: ['床', 'bed'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_wood_walnut' }],
  }),
  e('bunk_bed_a', '上下舖', 'Bunk bed', 'bedroom', [1000, 2000, 1650], pm('bunk_bed'), {
    tags: ['床', 'bed'],
  }),
  e('crib_a', '嬰兒床', 'Crib', 'bedroom', [700, 1300, 950], pm('crib'), { tags: ['嬰兒床'] }),
  e('bench_bed_end', '床尾凳', 'Bed-end bench', 'bedroom', [1300, 400, 450], pm('bench'), {
    tags: ['床尾凳'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_velvet_green' }],
  }),
  e('mirror_floor', '全身鏡', 'Floor mirror', 'bedroom', [600, 60, 1700], pm('mirror'), { tags: ['鏡子'] }),
  // 書房／娛樂
  e('laptop_a', '筆記型電腦', 'Laptop', 'office', [340, 240, 230], pm('laptop'), { tags: ['電腦'] }),
  e('books_stack', '書堆', 'Book stack', 'decor', [260, 200, 180], pm('books'), { tags: ['書'] }),
  e('treadmill_a', '跑步機', 'Treadmill', 'office', [800, 1800, 1400], pm('treadmill'), {
    tags: ['跑步機', 'gym'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_metal_black' }],
  }),
  // 衛浴
  e('shower_900', '淋浴間', 'Shower enclosure', 'bathroom', [900, 900, 2000], pm('shower'), {
    tags: ['淋浴'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_metal_steel' }],
  }),
  e('mirror_bath', '浴室鏡', 'Bathroom mirror', 'bathroom', [800, 30, 700], pm('mirror'), {
    anchor: 'wall',
    elevationMm: 1150,
    tags: ['鏡子'],
  }),
  e('basin_double', '雙槽洗手台', 'Double vanity', 'bathroom', [1200, 500, 850], pm('basin'), {
    tags: ['洗手台'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_wood_walnut' }],
  }),
  // 玄關／收納
  e('coat_rack_a', '衣帽架', 'Coat rack', 'entry', [500, 500, 1800], pm('coat_rack'), {
    tags: ['衣帽架'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_wood_dark' }],
  }),
  e('bench_entry', '玄關穿鞋椅', 'Entry bench', 'entry', [1000, 350, 450], pm('bench'), { tags: ['穿鞋椅'] }),
  e('wall_shelf_900', '壁掛層板', 'Wall shelf', 'storage', [900, 220, 300], pm('wall_shelf'), {
    anchor: 'wall',
    elevationMm: 1400,
    tags: ['層板'],
  }),
  // 家電
  e('aircon_split', '分離式冷氣', 'Split air conditioner', 'living', [900, 250, 300], pm('aircon'), {
    anchor: 'wall',
    elevationMm: 2250,
    tags: ['冷氣', 'ac'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_paint_white' }],
  }),
  e('radiator_a', '電暖器', 'Radiator', 'living', [800, 120, 600], pm('radiator'), {
    tags: ['暖氣'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_paint_white' }],
  }),
  e('ceiling_fan_a', '吊扇', 'Ceiling fan', 'lighting', [1300, 1300, 400], pm('ceiling_fan'), {
    anchor: 'ceiling',
    tags: ['吊扇'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_wood_dark' }],
  }),
  // 裝飾
  e('wall_art_900', '裝飾畫', 'Wall art', 'decor', [900, 40, 650], pm('wall_art'), {
    anchor: 'wall',
    elevationMm: 1250,
    tags: ['掛畫', 'art'],
  }),
  e('wall_art_1500', '大幅裝飾畫', 'Large wall art', 'decor', [1500, 40, 900], pm('wall_art'), {
    anchor: 'wall',
    elevationMm: 1100,
    tags: ['掛畫', 'art'],
  }),
  e('clock_wall', '掛鐘', 'Wall clock', 'decor', [400, 50, 400], pm('clock'), {
    anchor: 'wall',
    elevationMm: 1700,
    tags: ['時鐘'],
  }),
  e('vase_tall', '落地花瓶', 'Tall vase', 'decor', [300, 300, 800], pm('vase'), {
    tags: ['花瓶'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_ceramic_terracotta' }],
  }),
  e('vase_small', '桌上花瓶', 'Table vase', 'decor', [160, 160, 300], pm('vase'), {
    tags: ['花瓶'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_ceramic_white' }],
  }),
  e('plant_tall', '大型植栽', 'Tall plant', 'decor', [700, 700, 1900], pm('plant'), { tags: ['植物'] }),
  e('plant_small', '桌上盆栽', 'Small plant', 'decor', [250, 250, 380], pm('plant'), { tags: ['植物'] }),
  e('pet_bed_a', '寵物床', 'Pet bed', 'decor', [700, 550, 220], pm('pet_bed'), {
    tags: ['寵物'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_fabric_grey' }],
  }),
  lamp(
    'neon_sign_a',
    '霓虹燈招牌',
    'Neon sign',
    [900, 40, 400],
    'neon_sign',
    'cyan',
    { kind: 'area', lumens: 300, offset: [0, 200, 25], size: { w: 820, h: 320 }, facing: 'front' },
    { anchor: 'wall', elevationMm: 1400, category: 'decor' },
  ),
  lamp(
    'candle_set',
    '蠟燭組',
    'Candles',
    [220, 120, 160],
    'candle',
    'amber',
    {
      kind: 'point',
      lumens: 36,
      offset: [0, 170, 0],
    },
    {
      category: 'decor',
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_ceramic_white' }],
    },
  ),
  lamp('lamp_floor_tripod', '三腳立燈', 'Tripod floor lamp', [550, 550, 1650], 'lamp_floor', '3000K', {
    kind: 'point',
    lumens: 1200,
    offset: [0, 1500, 0],
    castShadow: true,
  }),
  lamp(
    'lamp_pendant_trio',
    '三頭吊燈',
    'Pendant trio',
    [1200, 300, 500],
    'lamp_track',
    '2700K',
    { kind: 'spot', lumens: 1500, offset: [0, 0, 60], beamDeg: 80, castShadow: true },
    { anchor: 'ceiling' },
  ),
  lamp('led_strip_3000', 'LED 燈條 3m', 'LED strip 3m', [3000, 20, 12], 'led_strip', '3000K', {
    kind: 'area',
    lumens: 1200,
    offset: [0, 6, 0],
    size: { w: 3000, h: 16 },
    facing: 'up',
  }),

  // ── v1.2 門窗樣式庫（FE-PLAN-04）──────────────────────────
  e(
    'door_sliding_1800',
    '推拉門 180',
    'Sliding door 180',
    'openings',
    [1800, 40, 2200],
    pm('door', {
      w: int(1200, 3600, 1800, 'param.width'),
      h: int(1800, 2600, 2200, 'param.height'),
      style: styleParam('sliding', DOOR_STYLES),
    }),
    { anchor: 'wall', tags: ['door', '門', '推拉'] },
  ),
  e(
    'door_folding_2400',
    '折疊門 240',
    'Folding door 240',
    'openings',
    [2400, 40, 2200],
    pm('door', {
      w: int(1200, 4800, 2400, 'param.width'),
      h: int(1800, 2600, 2200, 'param.height'),
      style: styleParam('folding', DOOR_STYLES),
    }),
    { anchor: 'wall', tags: ['door', '門', '折疊'] },
  ),
  e(
    'door_pocket_900',
    '隱藏式拉門 90',
    'Pocket door 90',
    'openings',
    [900, 40, 2100],
    pm('door', {
      w: int(600, 1500, 900, 'param.width'),
      h: int(1800, 2600, 2100, 'param.height'),
      style: styleParam('pocket', DOOR_STYLES),
    }),
    { anchor: 'wall', tags: ['door', '門'] },
  ),
  e(
    'door_unequal_1200',
    '子母門 120',
    'Unequal double door',
    'openings',
    [1200, 40, 2100],
    pm('door', {
      w: int(1000, 1600, 1200, 'param.width'),
      h: int(1800, 2600, 2100, 'param.height'),
      style: styleParam('unequal', DOOR_STYLES),
    }),
    { anchor: 'wall', tags: ['door', '門', '大門'] },
  ),
  e(
    'door_arch_900',
    '拱門（無門扇）',
    'Arched passage',
    'openings',
    [900, 40, 2200],
    pm('door', {
      w: int(600, 2400, 900, 'param.width'),
      h: int(1800, 2800, 2200, 'param.height'),
      style: styleParam('arch', DOOR_STYLES),
    }),
    { anchor: 'wall', tags: ['door', '拱門'] },
  ),
  e(
    'window_casement_900',
    '推射窗 90',
    'Casement window 90',
    'openings',
    [900, 80, 1200],
    pm('window', {
      w: int(400, 2000, 900, 'param.width'),
      h: int(400, 2000, 1200, 'param.height'),
      sill: int(0, 1500, 900, 'param.sill'),
      style: styleParam('casement', WINDOW_STYLES),
    }),
    { anchor: 'wall', tags: ['window', '窗'] },
  ),
  e(
    'window_fixed_1500',
    '固定景觀窗 150',
    'Fixed picture window',
    'openings',
    [1500, 80, 1500],
    pm('window', {
      w: int(400, 4000, 1500, 'param.width'),
      h: int(400, 2600, 1500, 'param.height'),
      sill: int(0, 1500, 600, 'param.sill'),
      style: styleParam('fixed', WINDOW_STYLES),
    }),
    { anchor: 'wall', tags: ['window', '窗'] },
  ),
  e(
    'window_awning_800',
    '上懸窗 80',
    'Awning window',
    'openings',
    [800, 80, 600],
    pm('window', {
      w: int(400, 1800, 800, 'param.width'),
      h: int(300, 1200, 600, 'param.height'),
      sill: int(0, 2000, 1500, 'param.sill'),
      style: styleParam('awning', WINDOW_STYLES),
    }),
    { anchor: 'wall', tags: ['window', '窗', '浴室'] },
  ),
  e(
    'window_bay_2000',
    '凸窗 200',
    'Bay window 200',
    'openings',
    [2000, 500, 1600],
    pm('window', {
      w: int(1200, 4000, 2000, 'param.width'),
      h: int(800, 2400, 1600, 'param.height'),
      sill: int(0, 1200, 500, 'param.sill'),
      style: styleParam('bay', WINDOW_STYLES),
    }),
    { anchor: 'wall', tags: ['window', '窗', '凸窗'] },
  ),
  e(
    'window_corner_1500',
    '轉角窗',
    'Corner window',
    'openings',
    [1500, 80, 1800],
    pm('window', {
      w: int(600, 3000, 1500, 'param.width'),
      h: int(600, 2600, 1800, 'param.height'),
      sill: int(0, 1500, 500, 'param.sill'),
      style: styleParam('corner', WINDOW_STYLES),
    }),
    { anchor: 'wall', tags: ['window', '窗'] },
  ),
  // ── v1.2 結構元件（FE-PLAN-03）────────────────────────────
  e(
    'column_square_400',
    '方柱 40',
    'Square column',
    'structure',
    [400, 400, 2800],
    pm('column', {
      w: int(150, 1500, 400, 'param.width'),
      d: int(150, 1500, 400, 'param.depth'),
      h: int(1000, 6000, 2800, 'param.height'),
      shape: { type: 'enum', values: ['square', 'round'], default: 'square', labelKey: 'param.shape' },
    }),
    {
      tags: ['柱', 'column'],
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_paint_white' }],
    },
  ),
  e(
    'column_round_400',
    '圓柱 Ø40',
    'Round column',
    'structure',
    [400, 400, 2800],
    pm('column', {
      w: int(150, 1500, 400, 'param.width'),
      d: int(150, 1500, 400, 'param.depth'),
      h: int(1000, 6000, 2800, 'param.height'),
      shape: { type: 'enum', values: ['square', 'round'], default: 'round', labelKey: 'param.shape' },
    }),
    {
      tags: ['柱', 'column'],
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_stone_concrete' }],
    },
  ),
  e('beam_300', '樑', 'Beam', 'structure', [3000, 300, 500], pm('beam', sizeParams(3000, 300, 500)), {
    anchor: 'ceiling',
    tags: ['樑', 'beam'],
    materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_paint_white' }],
  }),
  e(
    'stairs_straight',
    '直梯',
    'Straight stairs',
    'structure',
    [1000, 3600, 2950],
    pm('stairs', {
      w: int(600, 2400, 1000, 'param.width'),
      d: int(1500, 8000, 3600, 'param.depth'),
      h: int(1000, 6000, 2950, 'param.height'),
      steps: int(3, 30, 16, 'param.steps'),
      shape: {
        type: 'enum',
        values: ['straight', 'l', 'u', 'spiral'],
        default: 'straight',
        labelKey: 'param.shape',
      },
    }),
    {
      tags: ['樓梯', 'stairs'],
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_wood_oak' }],
    },
  ),
  e(
    'stairs_l',
    'L 型梯',
    'L-shaped stairs',
    'structure',
    [2000, 2800, 2950],
    pm('stairs', {
      w: int(1400, 4000, 2000, 'param.width'),
      d: int(1400, 6000, 2800, 'param.depth'),
      h: int(1000, 6000, 2950, 'param.height'),
      steps: int(6, 30, 16, 'param.steps'),
      shape: {
        type: 'enum',
        values: ['straight', 'l', 'u', 'spiral'],
        default: 'l',
        labelKey: 'param.shape',
      },
    }),
    {
      tags: ['樓梯', 'stairs'],
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_wood_oak' }],
    },
  ),
  e(
    'stairs_u',
    'U 型梯',
    'U-shaped stairs',
    'structure',
    [2100, 2800, 2950],
    pm('stairs', {
      w: int(1400, 4000, 2100, 'param.width'),
      d: int(1400, 6000, 2800, 'param.depth'),
      h: int(1000, 6000, 2950, 'param.height'),
      steps: int(6, 30, 18, 'param.steps'),
      shape: {
        type: 'enum',
        values: ['straight', 'l', 'u', 'spiral'],
        default: 'u',
        labelKey: 'param.shape',
      },
    }),
    {
      tags: ['樓梯', 'stairs'],
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_wood_oak' }],
    },
  ),
  e(
    'stairs_spiral',
    '旋轉梯',
    'Spiral stairs',
    'structure',
    [1800, 1800, 2950],
    pm('stairs', {
      w: int(1200, 3000, 1800, 'param.width'),
      d: int(1200, 3000, 1800, 'param.depth'),
      h: int(1000, 6000, 2950, 'param.height'),
      steps: int(8, 30, 14, 'param.steps'),
      shape: {
        type: 'enum',
        values: ['straight', 'l', 'u', 'spiral'],
        default: 'spiral',
        labelKey: 'param.shape',
      },
    }),
    {
      tags: ['樓梯', 'stairs'],
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_metal_black' }],
    },
  ),
  e(
    'platform_1800',
    '和室架高地板',
    'Raised platform',
    'structure',
    [1800, 1800, 400],
    pm('platform', sizeParams(1800, 1800, 400)),
    {
      tags: ['架高', '和室', 'platform'],
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_wood_oak' }],
    },
  ),
  e(
    'railing_1200',
    '欄杆 120',
    'Railing',
    'structure',
    [1200, 50, 1000],
    pm('railing', sizeParams(1200, 50, 1000)),
    {
      tags: ['欄杆', 'railing'],
      materialSlots: [{ name: 'body', swappable: true, defaultMaterialId: 'mat_metal_black' }],
    },
  ),
  // ── v1.3 水電點位（FE-DOC-05）──────────────────────────
  e(
    'mep_outlet',
    '插座',
    'Outlet',
    'mep',
    [86, 12, 86],
    pm('mep', {
      point: { type: 'enum', values: ['outlet'], default: 'outlet', labelKey: 'param.mepPoint' },
    }),
    { tags: ['水電', '插座', 'outlet'], anchor: 'wall', elevationMm: 300, materialSlots: [] },
  ),
  e(
    'mep_outlet_counter',
    '檯面插座',
    'Counter outlet',
    'mep',
    [86, 12, 86],
    pm('mep', {
      point: {
        type: 'enum',
        values: ['outlet_counter'],
        default: 'outlet_counter',
        labelKey: 'param.mepPoint',
      },
    }),
    { tags: ['水電', '檯面插座', 'outlet_counter'], anchor: 'wall', elevationMm: 1100, materialSlots: [] },
  ),
  e(
    'mep_switch',
    '開關',
    'Switch',
    'mep',
    [86, 12, 86],
    pm('mep', {
      point: { type: 'enum', values: ['switch'], default: 'switch', labelKey: 'param.mepPoint' },
    }),
    { tags: ['水電', '開關', 'switch'], anchor: 'wall', elevationMm: 1200, materialSlots: [] },
  ),
  e(
    'mep_data',
    '網路孔',
    'Data port',
    'mep',
    [86, 12, 86],
    pm('mep', {
      point: { type: 'enum', values: ['data'], default: 'data', labelKey: 'param.mepPoint' },
    }),
    { tags: ['水電', '網路孔', 'data'], anchor: 'wall', elevationMm: 300, materialSlots: [] },
  ),
  e(
    'mep_tv',
    '電視孔',
    'TV port',
    'mep',
    [86, 12, 86],
    pm('mep', {
      point: { type: 'enum', values: ['tv'], default: 'tv', labelKey: 'param.mepPoint' },
    }),
    { tags: ['水電', '電視孔', 'tv'], anchor: 'wall', elevationMm: 300, materialSlots: [] },
  ),
  e(
    'mep_water_cold',
    '冷水給水',
    'Cold water',
    'mep',
    [60, 60, 60],
    pm('mep', {
      point: { type: 'enum', values: ['water_cold'], default: 'water_cold', labelKey: 'param.mepPoint' },
    }),
    { tags: ['水電', '冷水給水', 'water_cold'], anchor: 'wall', elevationMm: 500, materialSlots: [] },
  ),
  e(
    'mep_water_hot',
    '熱水給水',
    'Hot water',
    'mep',
    [60, 60, 60],
    pm('mep', {
      point: { type: 'enum', values: ['water_hot'], default: 'water_hot', labelKey: 'param.mepPoint' },
    }),
    { tags: ['水電', '熱水給水', 'water_hot'], anchor: 'wall', elevationMm: 500, materialSlots: [] },
  ),
  e(
    'mep_drain',
    '排水',
    'Drain',
    'mep',
    [110, 110, 20],
    pm('mep', {
      point: { type: 'enum', values: ['drain'], default: 'drain', labelKey: 'param.mepPoint' },
    }),
    { tags: ['水電', '排水', 'drain'], anchor: 'floor', materialSlots: [] },
  ),
  e(
    'mep_gas',
    '瓦斯',
    'Gas',
    'mep',
    [60, 60, 60],
    pm('mep', {
      point: { type: 'enum', values: ['gas'], default: 'gas', labelKey: 'param.mepPoint' },
    }),
    { tags: ['水電', '瓦斯', 'gas'], anchor: 'wall', elevationMm: 600, materialSlots: [] },
  ),
  e(
    'mep_ac',
    '冷氣電源／排水',
    'AC point',
    'mep',
    [86, 12, 86],
    pm('mep', {
      point: { type: 'enum', values: ['ac'], default: 'ac', labelKey: 'param.mepPoint' },
    }),
    { tags: ['水電', '冷氣電源／排水', 'ac'], anchor: 'wall', elevationMm: 2300, materialSlots: [] },
  ),
  // 草稿示範：授權未確認 → 不得 published（07、B5）
  e(
    'sofa_vendor_x',
    '廠商沙發（授權未確認）',
    'Vendor sofa (unverified)',
    'living',
    [2200, 950, 850],
    pm('sofa'),
    { status: 'draft', license: undefined },
  ),
];

/**
 * 〔假設〕參考單價（新台幣，P6 估價用）：取整數佔位值，未經市場查價，UI/報表一律標示「參考價」。
 * 門窗以開口對應的目錄項計價（見 core-geometry computeBOM 的 openingCatalogId）。
 */
export const ASSUMED_PRICES_TWD: Readonly<Record<string, number>> = {
  door_single_900: 8000,
  door_double_1500: 16000,
  window_1200: 9000,
  window_1800: 18000,
  cabinet_wardrobe_1800: 36000,
  cabinet_shoe_1200: 12000,
  cabinet_book_900: 7000,
  cabinet_sideboard_1600: 15000,
  sofa_3seat_a: 28000,
  sofa_2seat_a: 19000,
  armchair_a: 8500,
  table_coffee_a: 5500,
  table_side_a: 2500,
  tvstand_1800: 9000,
  rug_2000: 4500,
  table_dining_4: 12000,
  table_dining_6: 18000,
  chair_dining_a: 2800,
  bed_double_150: 22000,
  bed_queen_180: 30000,
  bed_single_90: 12000,
  nightstand_a: 3500,
  desk_dresser_a: 8000,
  desk_office_1400: 9500,
  chair_office_a: 6000,
  shelf_open_800: 3500,
  counter_base_600: 9000,
  counter_base_900: 12000,
  fridge_a: 35000,
  island_1500: 42000,
  toilet_a: 12000,
  basin_a: 9000,
  bathtub_1600: 28000,
  lamp_floor_a: 3800,
  lamp_pendant_a: 4200,
  lamp_table_a: 1600,
  lamp_wall_a: 1800,
  lamp_downlight_a: 650,
  lamp_track_a: 2400,
  lamp_chandelier_a: 12000,
  lamp_arc_a: 5200,
  light_hex_a: 3200,
  led_strip_1000: 450,
  led_bar_1200: 1200,
  monitor_27: 7500,
  curtain_pair: 6500,
  plant_a: 1500,
  door_sliding_1800: 22000,
  door_folding_2400: 32000,
  door_pocket_900: 16000,
  door_unequal_1200: 26000,
  door_arch_900: 9000,
  window_casement_900: 8500,
  window_fixed_1500: 12000,
  window_awning_800: 6800,
  window_bay_2000: 38000,
  window_corner_1500: 24000,
  mep_outlet: 300,
  mep_outlet_counter: 350,
  mep_switch: 300,
  mep_data: 450,
  mep_tv: 450,
  mep_water_cold: 1500,
  mep_water_hot: 1800,
  mep_drain: 1500,
  mep_gas: 2500,
  mep_ac: 1200,
  column_square_400: 0,
  column_round_400: 0,
  beam_300: 0,
  stairs_straight: 68000,
  stairs_l: 88000,
  stairs_u: 98000,
  stairs_spiral: 120000,
  platform_1800: 36000,
  railing_1200: 7200,
  sofa_l_2700: 52000,
  sofa_leather_3: 46000,
  armchair_velvet: 12000,
  ottoman_round: 3200,
  bean_bag_a: 2800,
  floor_cushion_a: 900,
  table_coffee_round: 7800,
  tv_65: 32000,
  tv_55_wall: 22000,
  piano_upright: 120000,
  fireplace_electric: 26000,
  rug_round_2000: 5200,
  rug_3000: 9800,
  table_dining_round: 14000,
  bench_dining: 5200,
  stool_bar: 2600,
  bar_counter_1800: 28000,
  stove_600: 18000,
  sink_900: 16000,
  upper_cabinet_900: 8000,
  range_hood_900: 12000,
  cabinet_pantry_600: 15000,
  washer_a: 22000,
  dresser_1200: 11000,
  bed_king_200: 38000,
  bunk_bed_a: 18000,
  crib_a: 9000,
  bench_bed_end: 6500,
  mirror_floor: 3200,
  laptop_a: 35000,
  books_stack: 800,
  treadmill_a: 25000,
  shower_900: 26000,
  mirror_bath: 2800,
  basin_double: 24000,
  coat_rack_a: 1800,
  bench_entry: 3500,
  wall_shelf_900: 1600,
  aircon_split: 32000,
  radiator_a: 3500,
  ceiling_fan_a: 6800,
  wall_art_900: 2400,
  wall_art_1500: 4800,
  clock_wall: 1200,
  vase_tall: 2200,
  vase_small: 680,
  plant_tall: 3200,
  plant_small: 450,
  pet_bed_a: 1500,
  neon_sign_a: 4200,
  candle_set: 600,
  lamp_floor_tripod: 4600,
  lamp_pendant_trio: 7800,
  led_strip_3000: 1100,
};

/** 風格標籤（資產篩選用，FE-AST-02）：依預設材質推定；〔假設〕人工標註前的初值 */
export const STYLE_TAGS = [
  'modern',
  'nordic',
  'japandi',
  'industrial',
  'classic',
  'luxury',
  'midcentury',
  'minimal',
] as const;
const STYLE_BY_MATERIAL: Record<string, string[]> = {
  mat_wood_oak: ['nordic', 'japandi', 'modern'],
  mat_wood_walnut: ['midcentury', 'modern'],
  mat_wood_dark: ['midcentury', 'classic'],
  mat_metal_black: ['industrial', 'modern', 'minimal'],
  mat_metal_brass: ['luxury', 'classic'],
  mat_metal_steel: ['modern', 'minimal'],
  mat_fabric_beige: ['nordic', 'japandi'],
  mat_fabric_grey: ['modern', 'minimal', 'nordic'],
  mat_fabric_charcoal: ['modern', 'industrial'],
  mat_velvet_green: ['luxury', 'classic', 'midcentury'],
  mat_velvet_rust: ['midcentury', 'classic'],
  mat_leather_cognac: ['industrial', 'midcentury'],
  mat_stone_marble: ['luxury', 'modern'],
  mat_stone_concrete: ['industrial', 'minimal'],
  mat_paint_white: ['modern', 'minimal', 'nordic'],
  mat_lacquer_black: ['luxury', 'classic'],
  mat_ceramic_white: ['minimal', 'nordic'],
  mat_ceramic_terracotta: ['japandi', 'midcentury'],
};

export const SEED_CATALOG: CatalogEntry[] = ENTRIES.map((x) => {
  const priced =
    x.status === 'published' && x.unitPriceTwd === undefined && ASSUMED_PRICES_TWD[x.id] !== undefined
      ? { ...x, unitPriceTwd: ASSUMED_PRICES_TWD[x.id] }
      : x;
  const mat = priced.materialSlots[0]?.defaultMaterialId ?? '';
  const styles = STYLE_BY_MATERIAL[mat] ?? ['modern'];
  return { ...priced, styleTags: [...new Set([...styles, ...priced.styleTags])] };
});

const OWN = OWN_LICENSE;
export const SEED_MATERIALS: Material[] = [
  {
    id: 'mat_paint_white',
    nameZh: '白色乳膠漆',
    nameEn: 'White paint',
    category: 'wall',
    color: '#F2F0EB',
    pattern: 'plain',
    realSizeMm: { w: 1000, h: 1000 },
    roughness: 0.9,
    pricePerM2Twd: 350,
    license: OWN,
  },
  {
    id: 'mat_paint_sage',
    nameZh: '鼠尾草綠漆',
    nameEn: 'Sage paint',
    category: 'wall',
    color: '#A7B5A0',
    pattern: 'plain',
    realSizeMm: { w: 1000, h: 1000 },
    roughness: 0.9,
    pricePerM2Twd: 380,
    license: OWN,
  },
  {
    id: 'mat_paint_grey',
    nameZh: '暖灰漆',
    nameEn: 'Warm grey paint',
    category: 'wall',
    color: '#B9B4AB',
    pattern: 'plain',
    realSizeMm: { w: 1000, h: 1000 },
    roughness: 0.9,
    pricePerM2Twd: 380,
    license: OWN,
  },
  {
    id: 'mat_tile_white',
    nameZh: '白色壁磚 30×60',
    nameEn: 'White tile 30x60',
    category: 'wall',
    color: '#EDEDEA',
    pattern: 'tile',
    realSizeMm: { w: 600, h: 300 },
    roughness: 0.4,
    pricePerM2Twd: 1800,
    license: OWN,
  },
  {
    id: 'mat_wood_oak',
    nameZh: '淺橡木地板',
    nameEn: 'Light oak floor',
    category: 'floor',
    color: '#C8A77E',
    pattern: 'wood',
    realSizeMm: { w: 1200, h: 190 },
    roughness: 0.6,
    pricePerM2Twd: 3200,
    license: OWN,
  },
  {
    id: 'mat_wood_walnut',
    nameZh: '胡桃木地板',
    nameEn: 'Walnut floor',
    category: 'floor',
    color: '#6E4B32',
    pattern: 'wood',
    realSizeMm: { w: 1200, h: 190 },
    roughness: 0.55,
    pricePerM2Twd: 4200,
    license: OWN,
  },
  {
    id: 'mat_tile_grey60',
    nameZh: '灰色地磚 60×60',
    nameEn: 'Grey tile 60x60',
    category: 'floor',
    color: '#A9A8A3',
    pattern: 'tile',
    realSizeMm: { w: 600, h: 600 },
    roughness: 0.5,
    pricePerM2Twd: 2200,
    license: OWN,
  },
  {
    id: 'mat_stone_terrazzo',
    nameZh: '磨石子',
    nameEn: 'Terrazzo',
    category: 'floor',
    color: '#D5D0C6',
    pattern: 'stone',
    realSizeMm: { w: 800, h: 800 },
    roughness: 0.45,
    pricePerM2Twd: 3800,
    license: OWN,
  },
  {
    id: 'mat_ceiling_white',
    nameZh: '天花板白',
    nameEn: 'Ceiling white',
    category: 'ceiling',
    color: '#FAFAF7',
    pattern: 'plain',
    realSizeMm: { w: 1000, h: 1000 },
    roughness: 0.95,
    pricePerM2Twd: 300,
    license: OWN,
  },
  {
    id: 'mat_fabric_beige',
    nameZh: '米色布',
    nameEn: 'Beige fabric',
    category: 'fabric',
    color: '#D8CBB5',
    pattern: 'plain',
    realSizeMm: { w: 300, h: 300 },
    roughness: 0.95,
    license: OWN,
  },
  {
    id: 'mat_fabric_charcoal',
    nameZh: '炭灰布',
    nameEn: 'Charcoal fabric',
    category: 'fabric',
    color: '#4A4B4F',
    pattern: 'plain',
    realSizeMm: { w: 300, h: 300 },
    roughness: 0.95,
    license: OWN,
  },
  {
    id: 'mat_fabric_grey',
    nameZh: '淺灰布',
    nameEn: 'Light grey fabric',
    category: 'fabric',
    color: '#9C9A96',
    pattern: 'plain',
    realSizeMm: { w: 300, h: 300 },
    roughness: 0.95,
    license: OWN,
  },
  {
    id: 'mat_velvet_green',
    nameZh: '墨綠絨布',
    nameEn: 'Green velvet',
    category: 'fabric',
    color: '#3F5A4A',
    pattern: 'plain',
    realSizeMm: { w: 300, h: 300 },
    roughness: 0.8,
    license: OWN,
  },
  {
    id: 'mat_velvet_rust',
    nameZh: '鐵鏽紅絨布',
    nameEn: 'Rust velvet',
    category: 'fabric',
    color: '#9A4E32',
    pattern: 'plain',
    realSizeMm: { w: 300, h: 300 },
    roughness: 0.8,
    license: OWN,
  },
  {
    id: 'mat_leather_cognac',
    nameZh: '干邑色皮革',
    nameEn: 'Cognac leather',
    category: 'fabric',
    color: '#8A5230',
    pattern: 'plain',
    realSizeMm: { w: 300, h: 300 },
    roughness: 0.45,
    license: OWN,
  },
  {
    id: 'mat_wood_dark',
    nameZh: '深色胡桃木',
    nameEn: 'Dark walnut',
    category: 'wood',
    color: '#4A3322',
    pattern: 'wood',
    realSizeMm: { w: 1200, h: 190 },
    roughness: 0.5,
    license: OWN,
  },
  {
    id: 'mat_wood_herringbone',
    nameZh: '人字拼橡木',
    nameEn: 'Herringbone oak',
    category: 'floor',
    color: '#B8905F',
    pattern: 'wood',
    realSizeMm: { w: 600, h: 120 },
    roughness: 0.45,
    pricePerM2Twd: 5200,
    license: OWN,
  },
  {
    id: 'mat_stone_marble',
    nameZh: '白色大理石',
    nameEn: 'White marble',
    category: 'stone',
    color: '#E8E6E1',
    pattern: 'stone',
    realSizeMm: { w: 800, h: 800 },
    roughness: 0.2,
    pricePerM2Twd: 6800,
    license: OWN,
  },
  {
    id: 'mat_stone_concrete',
    nameZh: '清水模',
    nameEn: 'Exposed concrete',
    category: 'wall',
    color: '#A3A19C',
    pattern: 'stone',
    realSizeMm: { w: 1200, h: 600 },
    roughness: 0.85,
    pricePerM2Twd: 2600,
    license: OWN,
  },
  {
    id: 'mat_tile_black',
    nameZh: '黑色霧面地磚',
    nameEn: 'Matte black tile',
    category: 'floor',
    color: '#34332F',
    pattern: 'tile',
    realSizeMm: { w: 600, h: 600 },
    roughness: 0.55,
    pricePerM2Twd: 2600,
    license: OWN,
  },
  {
    id: 'mat_paint_navy',
    nameZh: '海軍藍漆',
    nameEn: 'Navy paint',
    category: 'wall',
    color: '#2F3E55',
    pattern: 'plain',
    realSizeMm: { w: 1000, h: 1000 },
    roughness: 0.9,
    pricePerM2Twd: 420,
    license: OWN,
  },
  {
    id: 'mat_paint_terracotta',
    nameZh: '陶土橘漆',
    nameEn: 'Terracotta paint',
    category: 'wall',
    color: '#C4775A',
    pattern: 'plain',
    realSizeMm: { w: 1000, h: 1000 },
    roughness: 0.9,
    pricePerM2Twd: 420,
    license: OWN,
  },
  {
    id: 'mat_lacquer_black',
    nameZh: '黑色鋼琴烤漆',
    nameEn: 'Black lacquer',
    category: 'wood',
    color: '#141414',
    pattern: 'plain',
    realSizeMm: { w: 500, h: 500 },
    roughness: 0.12,
    license: OWN,
  },
  {
    id: 'mat_metal_brass',
    nameZh: '黃銅',
    nameEn: 'Brass',
    category: 'metal',
    color: '#B08A48',
    pattern: 'plain',
    realSizeMm: { w: 500, h: 500 },
    roughness: 0.3,
    metalness: 1,
    license: OWN,
  },
  {
    id: 'mat_metal_steel',
    nameZh: '不鏽鋼',
    nameEn: 'Stainless steel',
    category: 'metal',
    color: '#B5B7B8',
    pattern: 'plain',
    realSizeMm: { w: 500, h: 500 },
    roughness: 0.28,
    metalness: 1,
    license: OWN,
  },
  {
    id: 'mat_ceramic_white',
    nameZh: '白瓷',
    nameEn: 'White ceramic',
    category: 'stone',
    color: '#F1EFEA',
    pattern: 'plain',
    realSizeMm: { w: 300, h: 300 },
    roughness: 0.25,
    license: OWN,
  },
  {
    id: 'mat_ceramic_terracotta',
    nameZh: '陶土',
    nameEn: 'Terracotta',
    category: 'stone',
    color: '#B5673F',
    pattern: 'plain',
    realSizeMm: { w: 300, h: 300 },
    roughness: 0.8,
    license: OWN,
  },
  {
    id: 'mat_metal_black',
    nameZh: '黑鐵',
    nameEn: 'Black metal',
    category: 'metal',
    color: '#2B2B2B',
    pattern: 'plain',
    realSizeMm: { w: 500, h: 500 },
    roughness: 0.4,
    metalness: 0.7,
    license: OWN,
  },
];
