/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康檢查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 註冊（本機 AuthProvider；建立個人組織並贈送點數） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResult"];
                    };
                };
                409: components["responses"]["Err"];
                422: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登入 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Credentials"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResult"];
                    };
                };
                401: components["responses"]["Err"];
                429: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 換發 token（refresh token 輪替；重用舊 token 會撤銷整個 token 家族） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResult"];
                    };
                };
                401: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（撤銷 refresh token 家族） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description ok */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 目前使用者 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Err"];
            };
        };
        put?: never;
        post?: never;
        /** 刪除帳號與衍生資料 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 專案列表 */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: {
                    /** @description 切換作用中的組織（須為成員） */
                    "X-Org-Id"?: components["parameters"]["OrgId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectPage"];
                    };
                };
            };
        };
        put?: never;
        /** 建立專案 */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description 切換作用中的組織（須為成員） */
                    "X-Org-Id"?: components["parameters"]["OrgId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectCreate"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                403: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** 取得專案 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                404: components["responses"]["Err"];
            };
        };
        put?: never;
        post?: never;
        /** 刪除專案（軟刪除） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** 更新專案中繼資料 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectPatch"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/projects/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** 版本列表（新到舊） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Version"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 儲存新版本（樂觀鎖；內容與目前版本相同時回 200 與既有版本） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VersionCreate"];
                };
            };
            responses: {
                /** @description 內容未變，回目前版本 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Version"];
                    };
                };
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Version"];
                    };
                };
                409: components["responses"]["Err"];
                422: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** 取得版本（含 Scene） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionWithScene"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/restore/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                versionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 還原版本（把目前版本指回該版本；版本本身不可變） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 建立上傳（回預簽名 URL；型別/大小不符回 422 UPLOAD_REJECTED，DWG 預設拒絕） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UploadCreate"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadTicket"];
                    };
                };
                422: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 完成上傳並檢查（大小、檔頭 magic bytes 與宣告的 mime 一致） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Upload"];
                    };
                };
                422: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 建立平面圖辨識任務（DXF／PNG／JPG／WEBP；非同步，進度走 /jobs/{id}） */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanImportCreate"];
                };
            };
            responses: {
                /** @description accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                404: components["responses"]["Err"];
                422: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** 取得辨識結果（PlanResult＋信心度；scale.method=unknown 時只有像素草稿，必須先校正尺度） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanImport"];
                    };
                };
                404: components["responses"]["Err"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 資產搜尋（只回 published） */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    category?: string;
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetPage"];
                    };
                };
            };
        };
        put?: never;
        /** 使用者上傳資產（進審核，status=review） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssetCreate"];
                };
            };
            responses: {
                /** @description accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                409: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** 資產詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 材質列表（published） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MaterialList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 點數價目（〔假設〕待商業定價；前端送出前顯示預估） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            render: {
                                "1k": number;
                                "2k": number;
                                "4k": number;
                            };
                            inpaint: number;
                            styles: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/renders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 建立渲染任務（預扣點數；4K 需 confirmHighRes） */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RenderRequest"];
                };
            };
            responses: {
                /** @description accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                402: components["responses"]["Err"];
                404: components["responses"]["Err"];
                422: components["responses"]["Err"];
                423: components["responses"]["Err"];
                429: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/renders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** 取得渲染結果（含預簽名 URL 與 provenance） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Render"];
                    };
                };
                404: components["responses"]["Err"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/renders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消（退回預扣點數） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                409: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/renders/{id}/inpaint": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 局部重繪（遮罩由所選物件的 objectId 產生；遮罩外像素逐位元還原） */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InpaintRequest"];
                };
            };
            responses: {
                /** @description accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                402: components["responses"]["Err"];
                404: components["responses"]["Err"];
                409: components["responses"]["Err"];
                422: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/renders/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 仍要使用未通過驗證的結果（以 adjust 帳本項目扣回實際成本後提供無浮水印下載，ADR-012 §5） */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Render"];
                    };
                };
                402: components["responses"]["Err"];
                409: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** 任務狀態 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                404: components["responses"]["Err"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** SSE 進度串流（event=job，data=Job；終態後關閉） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消任務（queued/running → canceled，預扣點數退回） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                409: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 助理（只回結構化提案，不改資料） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 餘額 */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description 切換作用中的組織（須為成員） */
                    "X-Org-Id"?: components["parameters"]["OrgId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Credits"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 帳本（新到舊） */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: {
                    /** @description 切換作用中的組織（須為成員） */
                    "X-Org-Id"?: components["parameters"]["OrgId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LedgerPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 建立結帳（v1 只有 mock 金流） */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckoutRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckoutSession"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 金流 webhook（HMAC-SHA256 驗簽，標頭 X-Signature；同一事件 id 只入帳一次） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PaymentEvent"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                401: components["responses"]["Err"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 建立分享連結 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 撤銷 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 匯出（png/jpg/pdf/dxf/glb/csv） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 匯出個人資料 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ErrorCode: "AUTH_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "VALIDATION_FAILED" | "VERSION_CONFLICT" | "INSUFFICIENT_CREDITS" | "RATE_LIMITED" | "UPLOAD_REJECTED" | "MODERATION_BLOCKED" | "JOB_FAILED" | "PROVIDER_UNAVAILABLE" | "SCHEMA_UNSUPPORTED" | "SCENE_LIMIT_EXCEEDED" | "IDEMPOTENCY_KEY_REUSED" | "SCALE_UNKNOWN" | "CONFLICT" | "CREDITS_FROZEN" | "INTERNAL";
        Error: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            details?: unknown;
            requestId: string;
        };
        /** @enum {string} */
        OrgRole: "owner" | "admin" | "editor" | "viewer";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName?: string | null;
            locale: string;
        };
        Me: components["schemas"]["User"] & {
            /** Format: uuid */
            activeOrgId: string;
            orgs: {
                /** Format: uuid */
                id: string;
                name: string;
                role: components["schemas"]["OrgRole"];
                plan: string;
            }[];
        };
        Credentials: {
            /** Format: email */
            email: string;
            password: string;
        };
        Register: {
            /** Format: email */
            email: string;
            password: string;
            displayName?: string;
            /** @enum {string} */
            locale?: "zh-TW" | "en";
        };
        /** @description refresh token 以 httpOnly cookie `rt` 回傳（Path=/v1/auth）；非瀏覽器用戶端可讀 refreshToken 欄位。 */
        AuthResult: {
            accessToken: string;
            refreshToken?: string;
            /** @description 秒 */
            expiresIn: number;
            user: components["schemas"]["User"];
        };
        RefreshRequest: {
            refreshToken?: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            thumbnailUrl?: string | null;
            /** Format: uuid */
            currentVersionId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectCreate: {
            name: string;
        };
        ProjectPatch: {
            name?: string;
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            nextCursor: string | null;
        };
        Version: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            parentVersionId?: string | null;
            schemaVersion: string;
            contentHash: string;
            note?: string | null;
            /** Format: uuid */
            createdBy?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        VersionWithScene: components["schemas"]["Version"] & {
            scene: components["schemas"]["scene.schema"];
        };
        VersionCreate: {
            /** Format: uuid */
            baseVersionId: string | null;
            scene: components["schemas"]["scene.schema"];
            note?: string;
        };
        /** @description 409 的 details：目前最新版本 */
        VersionConflict: {
            latest: components["schemas"]["Version"];
        };
        /** @enum {string} */
        UploadKind: "plan" | "photo" | "gbuffer" | "asset" | "other";
        UploadCreate: {
            kind: components["schemas"]["UploadKind"];
            filename: string;
            mime: string;
            sizeBytes: number;
            sha256?: string;
        };
        Upload: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["UploadKind"];
            mime: string;
            sizeBytes: number;
            /** @enum {string} */
            status: "pending" | "uploaded" | "rejected";
            /** Format: date-time */
            createdAt: string;
        };
        UploadTicket: {
            upload: components["schemas"]["Upload"];
            putUrl: string;
            headers: {
                [key: string]: string;
            };
            expiresIn: number;
        };
        Dims: {
            w: number;
            d: number;
            h: number;
        };
        License: {
            type: string;
            source: string;
            allowedUse?: string[];
            attribution?: string;
        };
        Asset: {
            /** Format: uuid */
            id: string;
            slug: string;
            nameZh: string;
            nameEn?: string | null;
            category: string;
            tags?: string[];
            styleTags?: string[];
            dimsMm: components["schemas"]["Dims"];
            /** @enum {string} */
            anchor: "floor" | "wall" | "ceiling";
            parametric?: Record<string, never> | null;
            materialSlots?: unknown[];
            license?: components["schemas"]["License"];
            /** @enum {string} */
            status: "draft" | "review" | "published" | "retired";
        };
        AssetCreate: {
            slug: string;
            nameZh: string;
            nameEn?: string;
            category: string;
            tags?: string[];
            dimsMm: components["schemas"]["Dims"];
            /** @enum {string} */
            anchor: "floor" | "wall" | "ceiling";
            /** Format: uuid */
            uploadId: string;
            license: components["schemas"]["License"];
        };
        AssetPage: {
            items: components["schemas"]["Asset"][];
            nextCursor: string | null;
        };
        Material: {
            /** Format: uuid */
            id: string;
            slug: string;
            nameZh: string;
            category: string;
            maps?: Record<string, never>;
            realSizeMm: {
                w: number;
                h: number;
            };
            status: string;
        };
        MaterialList: {
            items: components["schemas"]["Material"][];
        };
        /** @enum {string} */
        JobState: "queued" | "running" | "validating" | "succeeded" | "failed" | "canceled";
        Job: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "render" | "inpaint" | "plan_import" | "export" | "thumbnail" | "moderation";
            state: components["schemas"]["JobState"];
            progress: number;
            costEstimateCredits?: number;
            costActualCredits?: number | null;
            retryCount?: number;
            errorCode?: string | null;
            errorMessage?: string | null;
            output?: Record<string, never> | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        Credits: {
            balance: number;
            /** @description 對帳不一致時停止新預扣（ADR-014） */
            frozen: boolean;
        };
        LedgerEntry: {
            id: string;
            delta: number;
            /** @enum {string} */
            reason: "purchase" | "reserve" | "settle" | "refund" | "grant" | "adjust";
            /** Format: uuid */
            jobId?: string | null;
            balanceAfter: number;
            /** Format: date-time */
            createdAt: string;
        };
        LedgerPage: {
            items: components["schemas"]["LedgerEntry"][];
            nextCursor: string | null;
        };
        CheckoutRequest: {
            /** @enum {string} */
            packageId: "credits_50" | "credits_200";
        };
        CheckoutSession: {
            checkoutId: string;
            url: string;
            /** @description v1 只有 mock（真實金流未驗證） */
            provider: string;
        };
        PaymentEvent: {
            id: string;
            /** @enum {string} */
            type: "payment.succeeded";
            /** Format: uuid */
            orgId: string;
            credits: number;
        };
        Scene: components["schemas"]["scene.schema"];
        PlanImportCreate: {
            /** Format: uuid */
            uploadId: string;
            hints?: {
                scaleMmPerPx?: number;
            };
        };
        /** @description cv-service 的解析結果（06 §1）；units=px 表示尺度未知，座標為像素 */
        PlanResult: {
            /** @enum {string} */
            source: "vector" | "raster";
            /** @enum {string} */
            units: "mm" | "px";
            scale: {
                mmPerPx?: number | null;
                /** @enum {string} */
                method: "dimension_ocr" | "user" | "dxf_units" | "unknown";
                confidence?: number;
                suggestedMmPerPx?: number | null;
            } & {
                [key: string]: unknown;
            };
            walls: ({
                id: string;
                a: number[];
                b: number[];
                thickness: number;
                confidence: number;
            } & {
                [key: string]: unknown;
            })[];
            openings: ({
                id: string;
                wallId: string;
                /** @enum {string} */
                type: "door" | "window" | "passage";
                offset: number;
                width: number;
                height?: number;
                sill?: number;
                confidence: number;
            } & {
                [key: string]: unknown;
            })[];
            rooms?: ({
                polygon: number[][];
                label?: string | null;
                /** @description ocr | vlm | heuristic */
                labelSource?: string;
                confidence: number;
            } & {
                [key: string]: unknown;
            })[];
            labels?: {
                [key: string]: unknown;
            }[];
            image?: {
                [key: string]: unknown;
            } | null;
            warnings?: {
                code: string;
                message: string;
            }[];
        } & {
            [key: string]: unknown;
        };
        PlanImport: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            jobId: string;
            state: components["schemas"]["JobState"];
            progress: number;
            /** @enum {string|null} */
            source?: "vector" | "raster" | null;
            fileName?: string | null;
            /** @description 點陣原圖的預簽名 GET（校正 UI 疊圖用） */
            sourceUrl?: string | null;
            result?: components["schemas"]["PlanResult"] | null;
            errorCode?: string | null;
            errorMessage?: string | null;
        };
        RenderRequest: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            versionId: string;
            camera: {
                [key: string]: unknown;
            };
            gbufferUploadIds: {
                /** Format: uuid */
                color: string;
                /** Format: uuid */
                depth: string;
                /** Format: uuid */
                edge: string;
                /** Format: uuid */
                objectId: string;
                /** Format: uuid */
                normal?: string;
            };
            /** @description G-buffer objectId 顏色編碼（整數字串）→ 場景物件（局部重繪用） */
            idMap?: {
                [key: string]: {
                    id: string;
                    kind: string;
                };
            };
            settings: {
                /** @enum {string} */
                styleTemplateId: "modern" | "scandinavian" | "japandi" | "industrial" | "luxury";
                extra?: string;
                /** @enum {string} */
                strictness: "free" | "balanced" | "strict";
                /** @enum {string} */
                resolution: "1k" | "2k" | "4k";
                /** @description 4K 需使用者確認（B6.2-5） */
                confirmHighRes?: boolean;
                referenceUploadIds?: string[];
            };
        };
        InpaintRequest: {
            objectIds: string[];
            instruction: string;
        };
        Render: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            jobId: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            versionId?: string | null;
            /** @enum {string} */
            kind: "render" | "inpaint";
            /** Format: uuid */
            baseRenderId?: string | null;
            state: components["schemas"]["JobState"];
            progress: number;
            settings?: {
                [key: string]: unknown;
            };
            width?: number | null;
            height?: number | null;
            validation?: {
                score?: number | null;
                passed?: boolean | null;
                threshold?: number;
                calibrated?: boolean;
            } | null;
            /** @description 預簽名 GET（5 分鐘）；未通過驗證者須先 accept */
            outputUrl?: string | null;
            /** @description 未通過驗證時的 1K 浮水印預覽（不可下載原圖） */
            previewUrl?: string | null;
            /** @description 使用者選擇「仍要使用」未通過驗證的結果（ADR-012 §5） */
            accepted: boolean;
            costCredits: number;
            errorCode?: string | null;
            errorMessage?: string | null;
            provenance?: {
                [key: string]: unknown;
            } | null;
        };
        /** @description 程式產生用『前綴_ULID』；可讀 ID（如 w_01）僅限 fixtures（ADR-013） */
        id: string;
        mm: number;
        vec2: number[];
        hex: string;
        /** @description 外觀覆寫（v1.1，ADR-023）：只影響呈現 */
        appearance: {
            color?: components["schemas"]["hex"];
            roughness?: number;
            metalness?: number;
            opacity?: number;
            castShadow?: boolean;
            hidden?: boolean;
        };
        wall: {
            id: components["schemas"]["id"];
            a: components["schemas"]["vec2"];
            b: components["schemas"]["vec2"];
            thickness: number;
            /** @enum {unknown} */
            type?: "structural" | "exterior" | "partition" | "curtain";
            materialId?: components["schemas"]["id"];
            materialIdB?: components["schemas"]["id"];
            confidence?: number;
            height?: number;
            baseboard?: number;
            appearance?: components["schemas"]["appearance"];
            appearanceB?: components["schemas"]["appearance"];
        };
        opening: {
            id: components["schemas"]["id"];
            wallId: components["schemas"]["id"];
            /** @enum {unknown} */
            type: "door" | "window" | "passage";
            /** @description 從牆 a 端沿牆到開口起點的距離 */
            offset: number;
            width: number;
            height: number;
            /** @default 0 */
            sill: number;
            /** @enum {unknown} */
            swing?: "left" | "right" | "double" | "sliding" | "none";
            confidence?: number;
            appearance?: components["schemas"]["appearance"];
        };
        room: {
            id: components["schemas"]["id"];
            label?: string;
            wallIds: components["schemas"]["id"][];
            floorMaterialId?: components["schemas"]["id"];
            ceilingMaterialId?: components["schemas"]["id"];
            confidence?: number;
            floorAppearance?: components["schemas"]["appearance"];
            ceilingAppearance?: components["schemas"]["appearance"];
        };
        vec3: number[];
        /** @description 燈具光源覆寫（v1.1，ADR-023） */
        lightOverride: {
            on?: boolean;
            lumens?: number;
            kelvin?: number;
            color?: components["schemas"]["hex"];
            beamDeg?: number;
            penumbra?: number;
            tiltDeg?: number;
            panDeg?: number;
            castShadow?: boolean;
            shadowSoftness?: number;
            rangeMm?: number;
        };
        object: {
            id: components["schemas"]["id"];
            catalogId: components["schemas"]["id"];
            /** @description [x, y, z] mm；y 為離地高度 */
            position: components["schemas"]["vec3"];
            rotationY: number;
            scale?: number[];
            /** @description 參數化模組的參數 */
            params?: Record<string, never>;
            materialOverrides?: {
                [key: string]: components["schemas"]["id"];
            };
            locked?: boolean;
            roomId?: components["schemas"]["id"];
            name?: string;
            appearance?: components["schemas"]["appearance"];
            light?: components["schemas"]["lightOverride"];
        };
        annotation: {
            id: components["schemas"]["id"];
            /** @enum {unknown} */
            type: "dimension" | "text" | "note";
            data?: Record<string, never>;
        };
        level: {
            id: components["schemas"]["id"];
            name?: string;
            elevation: components["schemas"]["mm"];
            height: number;
            walls: components["schemas"]["wall"][];
            openings: components["schemas"]["opening"][];
            rooms: components["schemas"]["room"][];
            objects: components["schemas"]["object"][];
            annotations?: components["schemas"]["annotation"][];
        };
        camera: {
            id: components["schemas"]["id"];
            name?: string;
            position: components["schemas"]["vec3"];
            target: components["schemas"]["vec3"];
            fovDeg: number;
        };
        meta: {
            createdBy?: string;
            /** @enum {unknown} */
            source?: "manual" | "import-vector" | "import-raster" | "template";
            scale?: {
                /** @enum {unknown} */
                method?: "dimension_ocr" | "user" | "dxf_units" | "unknown";
            };
        } & {
            [key: string]: unknown;
        };
        /** @description 場景環境（v1.1） */
        environment: {
            /** @enum {unknown} */
            sky?: "moonless" | "moonlit" | "city" | "dusk";
            exposureEv?: number;
            ambient?: number;
            sunAzimuthDeg?: number;
            sunElevationDeg?: number;
            sunIntensity?: number;
        };
        /**
         * Scene Graph v1.1.0
         * @description 唯一事實來源。長度單位一律為 mm 整數；座標為 (x, z) 平面，Y 軸向上；角度為弧度。；上限與座標範圍為〔假設〕，見 ADR-013。
         */
        "scene.schema": {
            schemaVersion: string;
            /** @constant */
            units: "mm";
            levels: components["schemas"]["level"][];
            /** @description 命名視角書籤；視埠相機為 UI 暫態，不入 Scene（ADR-001） */
            cameras?: components["schemas"]["camera"][];
            meta?: components["schemas"]["meta"];
            environment?: components["schemas"]["environment"];
            $defs: {
                /** @description 程式產生用『前綴_ULID』；可讀 ID（如 w_01）僅限 fixtures（ADR-013） */
                id: string;
                mm: number;
                vec2: number[];
                vec3: number[];
                level: {
                    id: components["schemas"]["id"];
                    name?: string;
                    elevation: components["schemas"]["mm"];
                    height: number;
                    walls: components["schemas"]["wall"][];
                    openings: components["schemas"]["opening"][];
                    rooms: components["schemas"]["room"][];
                    objects: components["schemas"]["object"][];
                    annotations?: components["schemas"]["annotation"][];
                };
                wall: {
                    id: components["schemas"]["id"];
                    a: components["schemas"]["vec2"];
                    b: components["schemas"]["vec2"];
                    thickness: number;
                    /** @enum {unknown} */
                    type?: "structural" | "exterior" | "partition" | "curtain";
                    materialId?: components["schemas"]["id"];
                    materialIdB?: components["schemas"]["id"];
                    confidence?: number;
                    height?: number;
                    baseboard?: number;
                    appearance?: components["schemas"]["appearance"];
                    appearanceB?: components["schemas"]["appearance"];
                };
                opening: {
                    id: components["schemas"]["id"];
                    wallId: components["schemas"]["id"];
                    /** @enum {unknown} */
                    type: "door" | "window" | "passage";
                    /** @description 從牆 a 端沿牆到開口起點的距離 */
                    offset: number;
                    width: number;
                    height: number;
                    /** @default 0 */
                    sill: number;
                    /** @enum {unknown} */
                    swing?: "left" | "right" | "double" | "sliding" | "none";
                    confidence?: number;
                    appearance?: components["schemas"]["appearance"];
                };
                room: {
                    id: components["schemas"]["id"];
                    label?: string;
                    wallIds: components["schemas"]["id"][];
                    floorMaterialId?: components["schemas"]["id"];
                    ceilingMaterialId?: components["schemas"]["id"];
                    confidence?: number;
                    floorAppearance?: components["schemas"]["appearance"];
                    ceilingAppearance?: components["schemas"]["appearance"];
                };
                object: {
                    id: components["schemas"]["id"];
                    catalogId: components["schemas"]["id"];
                    /** @description [x, y, z] mm；y 為離地高度 */
                    position: components["schemas"]["vec3"];
                    rotationY: number;
                    scale?: number[];
                    /** @description 參數化模組的參數 */
                    params?: Record<string, never>;
                    materialOverrides?: {
                        [key: string]: components["schemas"]["id"];
                    };
                    locked?: boolean;
                    roomId?: components["schemas"]["id"];
                    name?: string;
                    appearance?: components["schemas"]["appearance"];
                    light?: components["schemas"]["lightOverride"];
                };
                annotation: {
                    id: components["schemas"]["id"];
                    /** @enum {unknown} */
                    type: "dimension" | "text" | "note";
                    data?: Record<string, never>;
                };
                camera: {
                    id: components["schemas"]["id"];
                    name?: string;
                    position: components["schemas"]["vec3"];
                    target: components["schemas"]["vec3"];
                    fovDeg: number;
                };
                meta: {
                    createdBy?: string;
                    /** @enum {unknown} */
                    source?: "manual" | "import-vector" | "import-raster" | "template";
                    scale?: {
                        /** @enum {unknown} */
                        method?: "dimension_ocr" | "user" | "dxf_units" | "unknown";
                    };
                } & {
                    [key: string]: unknown;
                };
                hex: string;
                /** @description 外觀覆寫（v1.1，ADR-023）：只影響呈現 */
                appearance: {
                    color?: components["schemas"]["hex"];
                    roughness?: number;
                    metalness?: number;
                    opacity?: number;
                    castShadow?: boolean;
                    hidden?: boolean;
                };
                /** @description 燈具光源覆寫（v1.1，ADR-023） */
                lightOverride: {
                    on?: boolean;
                    lumens?: number;
                    kelvin?: number;
                    color?: components["schemas"]["hex"];
                    beamDeg?: number;
                    penumbra?: number;
                    tiltDeg?: number;
                    panDeg?: number;
                    castShadow?: boolean;
                    shadowSoftness?: number;
                    rangeMm?: number;
                };
                /** @description 場景環境（v1.1） */
                environment: {
                    /** @enum {unknown} */
                    sky?: "moonless" | "moonlit" | "city" | "dusk";
                    exposureEv?: number;
                    ambient?: number;
                    sunAzimuthDeg?: number;
                    sunElevationDeg?: number;
                    sunIntensity?: number;
                };
            };
        };
    };
    responses: {
        /** @description Error */
        Err: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        Cursor: string;
        Limit: number;
        Id: string;
        /** @description 切換作用中的組織（須為成員） */
        OrgId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
